package twitterclonv2.common.util;

public enum Permission {
    UPDATE_POST,
    DELETE_POST,
    FIND_ALL_USERS,
    CREATE_ONE_POST,
    GET_USER_AUTHENTICATED,
    UPDATE_USER,
    SEARCH_USERS,
    CREATE_LIKE,
    DELETE_LIKE,
    FIND_ALL_POSTS_BY_USERNAME,
    FIND_ALL_POSTS,
    ADD_POST_TO_POSTS_SAVED,
    REMOVE_POST_FROM_POSTS_SAVED
}
