package twitterclonv2.common.util;

public enum Permission {
    UPDATE_POST,
    DELETE_POST,
    FIND_ALL_USERS,
    CREATE_ONE_POST,
    GET_USER_AUTHENTICATED,
    UPDATE_USER,
    SEARCH_USERS,
    LIKE_POST,
    REMOVE_LIKE_IN_POST,
    FIND_ALL_POSTS_OF_CURRENT_USER,
    FIND_ALL_POSTS
}
